# Generated by Django 3.2 on 2021-04-16 07:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='engi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=128)),
                ('content', models.TextField()),
                ('contents', models.URLField(default='')),
                ('image', models.ImageField(upload_to='web/engi')),
            ],
            options={
                'verbose_name': 'engi',
                'verbose_name_plural': 'engi',
                'db_table': 'web_engi',
            },
        ),
        migrations.CreateModel(
            name='med',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=128)),
                ('content', models.TextField()),
                ('contents', models.URLField(default='', editable=False)),
                ('image', models.ImageField(upload_to='web/med')),
            ],
            options={
                'verbose_name': 'med',
                'verbose_name_plural': 'med',
                'db_table': 'web_med',
            },
        ),
    ]
