# Generated by Django 3.2 on 2021-04-18 07:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0004_comm'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comm',
            name='phone',
            field=models.TextField(),
        ),
    ]
