# Generated by Django 3.2 on 2021-04-28 05:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0008_ff'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ff',
            new_name='animation',
        ),
        migrations.AlterModelOptions(
            name='animation',
            options={'verbose_name': 'animation', 'verbose_name_plural': 'animation'},
        ),
        migrations.AlterModelTable(
            name='animation',
            table='web_animation',
        ),
    ]
