# Generated by Django 3.2 on 2021-05-04 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0012_dental'),
    ]

    operations = [
        migrations.CreateModel(
            name='admisiion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'verbose_name': 'admission',
                'verbose_name_plural': 'admission',
                'db_table': 'web_admission',
            },
        ),
        migrations.CreateModel(
            name='search',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'verbose_name': 'search',
                'verbose_name_plural': 'search',
                'db_table': 'web_search',
            },
        ),
    ]
