# Generated by Django 3.2 on 2021-06-03 07:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0022_contact'),
    ]

    operations = [
        migrations.CreateModel(
            name='resource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=128)),
                ('content', models.TextField()),
            ],
            options={
                'verbose_name': 'resource',
                'verbose_name_plural': 'resource',
                'db_table': 'web_resource',
            },
        ),
    ]
