# Generated by Django 3.2 on 2021-06-03 07:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0023_resource'),
    ]

    operations = [
        migrations.AddField(
            model_name='resource',
            name='website',
            field=models.URLField(default=''),
        ),
    ]
