# Generated by Django 3.2 on 2021-06-22 06:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0025_auto_20210606_1349'),
    ]

    operations = [
        migrations.CreateModel(
            name='mass',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=128)),
                ('content', models.TextField()),
                ('contents', models.URLField(default='')),
                ('phone', models.TextField()),
                ('image', models.ImageField(upload_to='web/engi')),
            ],
            options={
                'verbose_name': 'mass',
                'verbose_name_plural': 'mass',
                'db_table': 'web_mass',
            },
        ),
    ]
